# Generated by Django 4.0.4 on 2023-07-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_stock_itemcreation_per_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_itemcreation',
            old_name='value',
            new_name='value1',
        ),
    ]
