# Generated by Django 4.0.4 on 2023-07-06 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_rename_value_stock_itemcreation_value1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_itemcreation',
            old_name='value1',
            new_name='value',
        ),
    ]
